# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x06\x63ommon\"\x07\n\x05\x45mpty\"/\n\x08Location\x12\x10\n\x08latitude\x18\x01 \x01(\x02\x12\x11\n\tlongitude\x18\x02 \x01(\x02*1\n\x08RideType\x12\x0b\n\x07\x44\x45\x46\x41ULT\x10\x00\x12\x0b\n\x07\x43OMFORT\x10\x01\x12\x0b\n\x07PREMIUM\x10\x02\x42\x0cZ\n./genprotob\x06proto3')

_RIDETYPE = DESCRIPTOR.enum_types_by_name['RideType']
RideType = enum_type_wrapper.EnumTypeWrapper(_RIDETYPE)
DEFAULT = 0
COMFORT = 1
PREMIUM = 2


_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_LOCATION = DESCRIPTOR.message_types_by_name['Location']
Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:common.Empty)
  })
_sym_db.RegisterMessage(Empty)

Location = _reflection.GeneratedProtocolMessageType('Location', (_message.Message,), {
  'DESCRIPTOR' : _LOCATION,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:common.Location)
  })
_sym_db.RegisterMessage(Location)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\n./genproto'
  _RIDETYPE._serialized_start=82
  _RIDETYPE._serialized_end=131
  _EMPTY._serialized_start=24
  _EMPTY._serialized_end=31
  _LOCATION._serialized_start=33
  _LOCATION._serialized_end=80
# @@protoc_insertion_point(module_scope)
