# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pricing.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpricing.proto\x12\x07pricing\x1a\x0c\x63ommon.proto\"H\n\x14\x43\x61lculateCostRequest\x12\x1e\n\x04type\x18\x01 \x01(\x0e\x32\x10.common.RideType\x12\x10\n\x08\x64istance\x18\x02 \x01(\x02\"%\n\x15\x43\x61lculateCostResponse\x12\x0c\n\x04\x63ost\x18\x01 \x01(\x02\x32`\n\x0ePricingService\x12N\n\rCalculateCost\x12\x1d.pricing.CalculateCostRequest\x1a\x1e.pricing.CalculateCostResponseb\x06proto3')



_CALCULATECOSTREQUEST = DESCRIPTOR.message_types_by_name['CalculateCostRequest']
_CALCULATECOSTRESPONSE = DESCRIPTOR.message_types_by_name['CalculateCostResponse']
CalculateCostRequest = _reflection.GeneratedProtocolMessageType('CalculateCostRequest', (_message.Message,), {
  'DESCRIPTOR' : _CALCULATECOSTREQUEST,
  '__module__' : 'pricing_pb2'
  # @@protoc_insertion_point(class_scope:pricing.CalculateCostRequest)
  })
_sym_db.RegisterMessage(CalculateCostRequest)

CalculateCostResponse = _reflection.GeneratedProtocolMessageType('CalculateCostResponse', (_message.Message,), {
  'DESCRIPTOR' : _CALCULATECOSTRESPONSE,
  '__module__' : 'pricing_pb2'
  # @@protoc_insertion_point(class_scope:pricing.CalculateCostResponse)
  })
_sym_db.RegisterMessage(CalculateCostResponse)

_PRICINGSERVICE = DESCRIPTOR.services_by_name['PricingService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CALCULATECOSTREQUEST._serialized_start=40
  _CALCULATECOSTREQUEST._serialized_end=112
  _CALCULATECOSTRESPONSE._serialized_start=114
  _CALCULATECOSTRESPONSE._serialized_end=151
  _PRICINGSERVICE._serialized_start=153
  _PRICINGSERVICE._serialized_end=249
# @@protoc_insertion_point(module_scope)
