// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: trip.proto

package genproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TripServiceClient is the client API for TripService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TripServiceClient interface {
	RequestTrip(ctx context.Context, in *RequestTripRequest, opts ...grpc.CallOption) (*RequestTripResponse, error)
	CancelTrip(ctx context.Context, in *CancelTripRequest, opts ...grpc.CallOption) (*Empty, error)
	SeekForTripAsDriver(ctx context.Context, opts ...grpc.CallOption) (TripService_SeekForTripAsDriverClient, error)
}

type tripServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTripServiceClient(cc grpc.ClientConnInterface) TripServiceClient {
	return &tripServiceClient{cc}
}

func (c *tripServiceClient) RequestTrip(ctx context.Context, in *RequestTripRequest, opts ...grpc.CallOption) (*RequestTripResponse, error) {
	out := new(RequestTripResponse)
	err := c.cc.Invoke(ctx, "/trip.TripService/RequestTrip", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) CancelTrip(ctx context.Context, in *CancelTripRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/trip.TripService/CancelTrip", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) SeekForTripAsDriver(ctx context.Context, opts ...grpc.CallOption) (TripService_SeekForTripAsDriverClient, error) {
	stream, err := c.cc.NewStream(ctx, &TripService_ServiceDesc.Streams[0], "/trip.TripService/SeekForTripAsDriver", opts...)
	if err != nil {
		return nil, err
	}
	x := &tripServiceSeekForTripAsDriverClient{stream}
	return x, nil
}

type TripService_SeekForTripAsDriverClient interface {
	Send(*SeekForTripAsDriverRequest) error
	Recv() (*SeekForTripAsDriverResponse, error)
	grpc.ClientStream
}

type tripServiceSeekForTripAsDriverClient struct {
	grpc.ClientStream
}

func (x *tripServiceSeekForTripAsDriverClient) Send(m *SeekForTripAsDriverRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *tripServiceSeekForTripAsDriverClient) Recv() (*SeekForTripAsDriverResponse, error) {
	m := new(SeekForTripAsDriverResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TripServiceServer is the server API for TripService service.
// All implementations must embed UnimplementedTripServiceServer
// for forward compatibility
type TripServiceServer interface {
	RequestTrip(context.Context, *RequestTripRequest) (*RequestTripResponse, error)
	CancelTrip(context.Context, *CancelTripRequest) (*Empty, error)
	SeekForTripAsDriver(TripService_SeekForTripAsDriverServer) error
	mustEmbedUnimplementedTripServiceServer()
}

// UnimplementedTripServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTripServiceServer struct {
}

func (UnimplementedTripServiceServer) RequestTrip(context.Context, *RequestTripRequest) (*RequestTripResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestTrip not implemented")
}
func (UnimplementedTripServiceServer) CancelTrip(context.Context, *CancelTripRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelTrip not implemented")
}
func (UnimplementedTripServiceServer) SeekForTripAsDriver(TripService_SeekForTripAsDriverServer) error {
	return status.Errorf(codes.Unimplemented, "method SeekForTripAsDriver not implemented")
}
func (UnimplementedTripServiceServer) mustEmbedUnimplementedTripServiceServer() {}

// UnsafeTripServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TripServiceServer will
// result in compilation errors.
type UnsafeTripServiceServer interface {
	mustEmbedUnimplementedTripServiceServer()
}

func RegisterTripServiceServer(s grpc.ServiceRegistrar, srv TripServiceServer) {
	s.RegisterService(&TripService_ServiceDesc, srv)
}

func _TripService_RequestTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestTripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).RequestTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trip.TripService/RequestTrip",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).RequestTrip(ctx, req.(*RequestTripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_CancelTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelTripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).CancelTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trip.TripService/CancelTrip",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).CancelTrip(ctx, req.(*CancelTripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_SeekForTripAsDriver_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TripServiceServer).SeekForTripAsDriver(&tripServiceSeekForTripAsDriverServer{stream})
}

type TripService_SeekForTripAsDriverServer interface {
	Send(*SeekForTripAsDriverResponse) error
	Recv() (*SeekForTripAsDriverRequest, error)
	grpc.ServerStream
}

type tripServiceSeekForTripAsDriverServer struct {
	grpc.ServerStream
}

func (x *tripServiceSeekForTripAsDriverServer) Send(m *SeekForTripAsDriverResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *tripServiceSeekForTripAsDriverServer) Recv() (*SeekForTripAsDriverRequest, error) {
	m := new(SeekForTripAsDriverRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TripService_ServiceDesc is the grpc.ServiceDesc for TripService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TripService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trip.TripService",
	HandlerType: (*TripServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestTrip",
			Handler:    _TripService_RequestTrip_Handler,
		},
		{
			MethodName: "CancelTrip",
			Handler:    _TripService_CancelTrip_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SeekForTripAsDriver",
			Handler:       _TripService_SeekForTripAsDriver_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "trip.proto",
}
